fastboot: Don't set device to null upon disconnect
Now that isConnected has been refactored, we don't need this anymore.
Remove it to fix race conditions causing the following error during
flashing:

TypeError: Cannot read property 'transferOut' of null